import { CITIES } from "@/data/cities";
import { DIMENSIONS, type CityProfile, type ClimatePreference, type LifeDimension, type LifeProfile, type Question } from "@/domain/types";
export const MATCHING_VERSION = "2026.08.v1";
const hash = (seed: string) => Array.from(seed).reduce((n, c) => ((n << 5) - n + c.charCodeAt(0)) | 0, 0) >>> 0;
const rng = (seed: string) => { let s = hash(seed) || 1; return () => ((s = (s * 1664525 + 1013904223) >>> 0) / 4294967296); };
const shuffle = <T,>(items: T[], random: () => number) => [...items].sort(() => random() - .5);
export function sampleQuestions(all: Question[], sessionId: string) { const random = rng(sessionId); const anchors = all.filter(q => q.anchor); const dynamics = all.filter(q => !q.anchor); const picked = [...anchors]; const chosenGroups = new Set(anchors.map(q => q.semanticGroup)); for (const d of DIMENSIONS) { const candidate = shuffle(dynamics.filter(q => q.primaryDimension === d && !chosenGroups.has(q.semanticGroup)), random)[0]; if (candidate) { picked.push(candidate); chosenGroups.add(candidate.semanticGroup); } } const remaining = shuffle(dynamics.filter(q => !chosenGroups.has(q.semanticGroup)), random); for (const q of remaining) { if (picked.length >= 28) break; if (picked.filter(x => x.primaryDimension === q.primaryDimension).length >= 3) continue; picked.push(q); chosenGroups.add(q.semanticGroup); } return shuffle(picked, random).map(q => ({ ...q, options: shuffle(q.options, random) })); }
const normalize = (value: number, count: number) => Math.max(0, Math.min(100, Math.round(((value / Math.max(count, 1)) + 3) / 6 * 100)));
export function scoreProfile(questions: Question[], answers: Record<string, string>): LifeProfile { if (questions.some(q => !answers[q.id])) throw new Error("请完成全部题目"); const sums = Object.fromEntries(DIMENSIONS.map(d => [d, 0])) as Record<LifeDimension, number>; const counts = Object.fromEntries(DIMENSIONS.map(d => [d, 0])) as Record<LifeDimension, number>; const climate = { warm: 0, cool: 0, dry: 0, humid: 0, sunny: 0 }; for (const q of questions) { counts[q.primaryDimension]++; const option = q.options.find(o => o.id === answers[q.id])!; for (const [key, value] of Object.entries(option.effects)) sums[key as LifeDimension] += value ?? 0; for (const [key, value] of Object.entries(option.climateEffects ?? {})) climate[key as keyof ClimatePreference] += value ?? 0; } const climateProfile: ClimatePreference = { warm: Math.round(((climate.warm / questions.length) + 1) / 2 * 100), cool: Math.round(((climate.cool / questions.length) + 1) / 2 * 100), dry: Math.round(((climate.dry / questions.length) + 1) / 2 * 100), humid: Math.round(((climate.humid / questions.length) + 1) / 2 * 100), sunny: Math.round(((climate.sunny / questions.length) + 1) / 2 * 100) }; return { ...Object.fromEntries(DIMENSIONS.map(d => [d, normalize(sums[d], counts[d])])) as Record<LifeDimension, number>, climate: climateProfile }; }
const similarity = (a: number, b: number) => 100 - Math.abs(a - b);
function cityScore(profile: LifeProfile, city: CityProfile, mode: "destiny" | "career" | "comfort") { const dims = mode === "career" ? { AMB: .34, NOV: .24, SOC: .18, ORDER: .24 } : mode === "comfort" ? { PACE: .25, NAT: .2, FOOD: .18, SPACE: .2, COST: .17 } : { AMB:.11, PACE:.11, SOC:.08, NAT:.09, ORDER:.1, CULT:.09, FOOD:.09, SPACE:.09, NOV:.09, ROOT:.06, COST:.09 }; let total = 0; for (const [d,w] of Object.entries(dims)) { const val = d === "COST" ? 100 - city.actualCostLevel : city.dimensions[d as keyof CityProfile["dimensions"]]; const desired = profile[d as LifeDimension]; total += similarity(desired, val) * w; } const climate = Object.keys(profile.climate).reduce((sum, key) => sum + similarity(profile.climate[key as keyof ClimatePreference], city.climate[key as keyof ClimatePreference]), 0) / 5; return total * .9 + climate * .1; }
export function matchCities(profile: LifeProfile) { const rank = (mode: "destiny" | "career" | "comfort") => CITIES.map(city => ({ city, score: Math.round(cityScore(profile, city, mode)), factors: city.strengths })).sort((a,b) => b.score-a.score); const destiny = rank("destiny"), career = rank("career"), comfort = rank("comfort"); const least = [...destiny].sort((a,b) => a.score-b.score)[0]; return { destiny, career, comfort, least }; }
export function coreTraits(profile: LifeProfile) { return [...DIMENSIONS].sort((a,b) => profile[b] - profile[a]).slice(0,3); }
