import { CITY_PROFILE_VERSION } from "@/data/cities";
import { coreTraits, MATCHING_VERSION } from "@/lib/engine";
import { MATCHING_CONFIG } from "@/lib/matching.config";
import type { CityResult, LifeProfile } from "@/domain/types";
import type { LeastCompatibleResult } from "@/lib/engine";
export type ReportContext = { sessionId:string; profile:LifeProfile; destiny:CityResult; career:CityResult; comfort:CityResult; least:LeastCompatibleResult | null; profileVersion:string };
export type GeneratedReport = { content:string; cacheKey:string };
export interface ReportProvider { generate(context:ReportContext): Promise<GeneratedReport> }
export const reportCacheKey=(context:ReportContext)=>[context.sessionId,context.profileVersion,CITY_PROFILE_VERSION,MATCHING_VERSION,MATCHING_CONFIG.reportPromptVersion].join(":");
export class FallbackReportProvider implements ReportProvider { async generate(c:ReportContext){ const traits=coreTraits(c.profile).join("、"); const city=c.destiny.city; const leastText=c.least?`${c.least.city.name} 出现了至少 ${c.least.meaningfulMismatchCount} 项显著不匹配，主要来自 ${c.least.factors.slice(0,3).join("、")}。这不代表它不好，只是它可能不容易支持你当前想过的生活。` : "你的生活偏好比较开放，没有特别明显“不适合”的城市。"; const content=`01 你的城市人格\n\n你当前更重视${traits}。这不是给你贴标签，而是说明：你需要的日常既要能托住目标，也要让人有余地持续生活。\n\n02 为什么你的命定城市是这里\n\n${city.name} 的${city.strengths[0]}，与这次测试里呈现出的生活需求形成了相对稳定的平衡。它不是唯一正确答案，只是一座值得认真考虑的候选城市。\n\n03 它最适合你的地方\n\n在这里，你可以把机会、日常和可恢复的节奏放到同一张生活地图里。对你来说，城市的价值不只是“能不能赢”，也是下班后还有没有完整的自己。\n\n04 它可能让你不舒服的地方\n\n${city.tradeoffs[0]}。适配不是消除摩擦，而是确认这些摩擦是否值得交换；如果它持续消耗你，就应当调整居住区、工作方式或城市选择。\n\n05 你的事业城市\n\n${c.career.city.name} 更容易放大你的职业动能：它在机会、变化与效率上的组合，更适合你阶段性冲刺。\n\n06 你的舒适城市\n\n${c.comfort.city.name} 更接近日常恢复的需求。它不代表你必须离开竞争，而是提醒你，舒服并不是懒散，而是一种可持续。\n\n07 最不适合你长期生活的城市\n\n${leastText}\n\n08 为什么一些城市会喜欢但住不久\n\n一座城市可以很适合旅行、短暂工作或恋爱，却未必适合日常。你真正需要的是长期能被重复的生活：通勤、吃饭、休息、关系与机会都能彼此照应。\n\n09 你真正想要的生活状态\n\n你的城市选择不该只回答“哪里更强”，而要回答“我希望怎样度过普通的一天”。把城市当作生活条件，而不是身份标签，会更接近你的答案。\n\n10 给你的城市选择建议\n\n如果要做决定，先用三个月实地体验目标城市的通勤、周末、消费和孤独时刻；再看它是否能支撑你想要的关系与工作。慢一点验证，比一次冲动迁移更可靠。`; return {content,cacheKey:reportCacheKey(c)}; } }
export class LLMReportProvider implements ReportProvider { constructor(private fallback:ReportProvider=new FallbackReportProvider()){} async generate(context:ReportContext){ return this.fallback.generate(context); } }
