"use client";
import { useEffect, useState } from "react";
import { dimensionLabel, QUESTIONS } from "@/data/questions";
import { coreTraits, matchCities, sampleQuestions, scoreProfile } from "@/lib/engine";
import { persistence, type SessionRecord } from "@/lib/persistence";
import { FallbackReportProvider } from "@/lib/report";
type Stage = "home" | "test" | "result";
type Stored = SessionRecord;
const id = () => typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
function save(data: Stored) { void persistence.saveSession(data); }
export default function Home() {
 const [stage,setStage]=useState<Stage>("home"), [data,setData]=useState<Stored|null>(null), [index,setIndex]=useState(0), [report,setReport]=useState("");
 const track=(name: Parameters<typeof persistence.track>[0],sessionId?:string,source?:string)=>void persistence.track(name,sessionId,source);
 useEffect(()=>{ const raw=localStorage.getItem("destiny-city-v3"); if(raw){ const stored=JSON.parse(raw) as Stored; setData(stored); setReport(stored.report?.content??""); if(stored.profile) setStage("result"); else { setStage("test"); setIndex(Object.keys(stored.answers).length); } } track("landing_view"); },[]);
 const begin=()=>{ const sessionId=id(); const acquisitionSource=new URLSearchParams(window.location.search).get("src")||"direct"; const next:Stored={sessionId,acquisitionSource,questions:sampleQuestions(QUESTIONS,sessionId),answers:{},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; setData(next); save(next); setIndex(0); setStage("test"); track("test_started",sessionId,acquisitionSource); };
 const answer=(answerId:string)=>{ if(!data)return; const q=data.questions[index]; const next={...data,answers:{...data.answers,[q.id]:answerId}}; setData(next); save(next); track("question_answered",data.sessionId); if(index<27) setIndex(index+1); else { const profile=scoreProfile(next.questions,next.answers); const ranks=matchCities(profile); const generated=new FallbackReportProvider().generate({sessionId:data.sessionId,profile,destiny:ranks.destiny[0],career:ranks.career[0],comfort:ranks.comfort[0],least:ranks.least,profileVersion:"2026.08.v2"}); void generated.then(value=>{const complete={...next,profile,report:{...value,createdAt:new Date().toISOString()}};setData(complete);setReport(value.content);save(complete);setStage("result");track("test_completed",data.sessionId);track("result_viewed",data.sessionId);track("report_viewed",data.sessionId);}); } };
 if(stage==="home") return <main className="landing"><nav><span className="wordmark">CITY / LIFE</span><span className="issue">FIELD NOTE · 01</span></nav><section className="hero"><p className="eyebrow">一份关于你和城市关系的生活方式观察</p><h1>也许你不是过得不好，<br/><i>只是住错了城市。</i></h1><p className="lead">28 个关于生活、工作和选择的问题，看看哪座城市更接近你真正想过的生活。</p><button onClick={begin}>开始测试 <span>→</span></button><p className="meta">28 道题 · 约 5 分钟 · 完成后直接查看完整结果</p></section><aside className="side-note">城市不是标准答案。<br/>它是你想怎样度过每一天的线索。</aside><footer>本测试用于娱乐、自我观察与生活方式探索，不构成职业、财务、移居或其他专业建议。</footer></main>;
 if(!data) return null;
 if(stage==="test") { const q=data.questions[index]; return <main className="test"><header><button className="plain" onClick={()=>setStage("home")}>×</button><span>{String(index+1).padStart(2,"0")} / 28</span><div className="bar"><i style={{width:`${(index+1)/28*100}%`}}/></div></header><section><p className="eyebrow">{q.scenario} · {dimensionLabel(q.primaryDimension)}</p><h2>{q.text}</h2><div className="options">{q.options.map((o,n)=><button key={o.id} onClick={()=>answer(o.id)}><b>0{n+1}</b>{o.text}<span>↗</span></button>)}</div></section><button className="previous" disabled={!index} onClick={()=>setIndex(index-1)}>← 返回上一题</button><p className="quiet">没有正确答案。请按你真实的生活偏好选择。</p></main>; }
 const profile=data.profile!; const ranks=matchCities(profile); const destiny=ranks.destiny[0]; const traits=coreTraits(profile); return <main className="result"><p className="eyebrow">你的完整城市观察 / {data.sessionId.slice(0,8)}</p><div className="result-top"><div><p className="kicker">你的命定城市</p><h1>{destiny.city.name}</h1><p className="verdict">你需要的不是一座完全慢下来的城市，而是一座还有机会、也允许你把生活留给自己的地方。</p></div><div className="score">{destiny.score}<small>适配度</small></div></div><section className="traits"><p>你的三个核心生活倾向</p>{traits.map(d=><div key={d}><span>{dimensionLabel(d)}</span><i><b style={{width:`${profile[d]}%`}}/></i><em>{profile[d]}</em></div>)}</section><article className="full-report">{report.split("\n\n").map((text,i)=>i%2===0?<Report key={text} title={text} text={report.split("\n\n")[i+1]??""}/>:null)}</article><ShareCard city={destiny.city.name} second={ranks.destiny[1].city.name} career={ranks.career[0].city.name} traits={traits.map(d=>dimensionLabel(d))} sessionId={data.sessionId} track={track}/><button className="restart" onClick={begin}>重新开始测试</button></main>;
}
function Report({title,text}:{title:string;text:string}){return <section className="report-section"><h2>{title}</h2><p>{text}</p></section>}
function ShareCard({city,second,career,traits,sessionId,track}:{city:string;second:string;career:string;traits:string[];sessionId:string;track:(name:Parameters<typeof persistence.track>[0],id?:string)=>void}){const download=()=>{const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1440;const c=canvas.getContext("2d")!;c.fillStyle="#dca96c";c.fillRect(0,0,1080,1440);c.fillStyle="#2e271f";c.font="34px serif";c.fillText("MY DESTINY CITY",85,105);c.font="58px serif";c.fillText("我的命定城市",85,210);c.font="bold 190px serif";c.fillText(city,85,430);c.font="42px serif";c.fillText("城市人格：温和探索型",85,560);c.font="36px serif";c.fillText(traits.join(" · "),85,1110);c.font="31px serif";c.fillText(`第二命定城市：${second}`,85,1260);c.fillText(`事业城市：${career}`,85,1320);c.fillText("你的命定城市",85,1380);const a=document.createElement("a");a.download=`我的命定城市-${city}.png`;a.href=canvas.toDataURL("image/png");a.click();track("share_card_generated",sessionId)};return <section className="share"><div className="share-card"><small>MY DESTINY CITY</small><h2>我的命定城市</h2><strong>{city}</strong><p>城市人格：<br/>温和探索型</p><p className="keywords">{traits.join(" · ")}</p><footer>第二命定城市：{second}<br/>事业城市：{career}</footer></div><button onClick={download}>保存 PNG 分享卡 <span>↓</span></button><small>1080 × 1440 PNG</small></section>}
