"use client";
import { useEffect, useState } from "react";
import { dimensionLabel, QUESTIONS } from "@/data/questions";
import { coreTraits, matchCities, sampleQuestions, scoreProfile } from "@/lib/engine";
import type { LifeProfile, Question } from "@/domain/types";
type Stage = "home" | "test" | "result" | "report";
type Stored = { sessionId: string; questions: Question[]; answers: Record<string,string>; profile?: LifeProfile };
const STORAGE = "destiny-city-v1";
const event = (name: string) => console.info("[destiny-city]", name);
const id = () => typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
function save(data: Stored) { localStorage.setItem(STORAGE, JSON.stringify(data)); }
export default function Home() {
 const [stage,setStage]=useState<Stage>("home"), [data,setData]=useState<Stored|null>(null), [index,setIndex]=useState(0), [locked,setLocked]=useState(true);
 useEffect(()=>{ const raw=localStorage.getItem(STORAGE); if(raw){ const stored=JSON.parse(raw) as Stored; setData(stored); if(stored.profile) setStage("result"); else { setStage("test"); setIndex(Object.keys(stored.answers).length); } } event("landing_view"); },[]);
 const begin=()=>{ const sessionId=id(); const next={sessionId,questions:sampleQuestions(QUESTIONS,sessionId),answers:{}}; setData(next); save(next); setIndex(0); setStage("test"); event("test_started"); };
 const answer=(answerId:string)=>{ if(!data)return; const q=data.questions[index]; const next={...data,answers:{...data.answers,[q.id]:answerId}}; setData(next); save(next); event("question_answered"); if(index<27) setIndex(index+1); else { const profile=scoreProfile(next.questions,next.answers); const complete={...next,profile}; setData(complete); save(complete); setStage("result"); event("test_completed"); event("free_result_viewed"); } };
 if(stage==="home") return <main className="landing"><nav><span className="wordmark">CITY / LIFE</span><span className="issue">FIELD NOTE · 01</span></nav><section className="hero"><p className="eyebrow">一份关于你和城市关系的生活方式观察</p><h1>你的<br/><i>命定</i>城市</h1><p className="lead">也许你不是过得不好，<br/>只是住错了城市。</p><button onClick={begin}>看看我应该住在哪里 <span>→</span></button><p className="meta">28 道题 · 约 5–7 分钟 · 无需登录</p></section><aside className="side-note">城市不是标准答案。<br/>它是你想怎样度过每一天的线索。</aside><footer>本测试用于娱乐、自我观察与生活方式探索，不构成职业、财务、移居或其他专业建议。</footer></main>;
 if(!data) return null;
 if(stage==="test") { const q=data.questions[index]; return <main className="test"><header><button className="plain" onClick={()=>{event("test_abandoned");setStage("home")}}>×</button><span>{String(index+1).padStart(2,"0")} / 28</span><div className="bar"><i style={{width:`${(index+1)/28*100}%`}}/></div></header><section><p className="eyebrow">{q.scenario} · {dimensionLabel(q.primaryDimension)}</p><h2>{q.text}</h2><div className="options">{q.options.map((o,n)=><button key={o.id} onClick={()=>answer(o.id)}><b>0{n+1}</b>{o.text}<span>↗</span></button>)}</div></section><p className="quiet">没有正确答案。请按你真实的生活偏好选择。</p></main>; }
 const profile=data.profile!; const ranks=matchCities(profile); const destiny=ranks.destiny[0]; const traits=coreTraits(profile); const full=()=>{setLocked(false);setStage("report");event("payment_completed");event("full_report_viewed")};
 if(stage==="result") return <main className="result"><p className="eyebrow">你的城市观察结果 / {data.sessionId.slice(0,8)}</p><div className="result-top"><div><p className="kicker">你的命定城市</p><h1>{destiny.city.name}</h1><p className="verdict">你需要的不是一座完全慢下来的城市，而是一座还有机会、也允许你把生活留给自己的地方。</p></div><div className="score">{destiny.score}<small>适配度</small></div></div><section className="traits"><p>你的三个核心生活倾向</p>{traits.map(d=><div key={d}><span>{dimensionLabel(d)}</span><i><b style={{width:`${profile[d]}%`}}/></i><em>{profile[d]}</em></div>)}</section><section className="paywall"><p className="kicker">你的城市人生报告</p><h2>你不只适合 <i>{destiny.city.name}</i></h2><ul><li>最适合事业发展的城市</li><li>最适合舒服生活的城市</li><li>最不适合长期居住的城市</li><li>你的城市人格与人生建议</li></ul><button onClick={full}>{locked?"解锁完整城市报告 · 开发体验":"查看完整报告"} <span>→</span></button><small>开发模式已开启，无需真实支付</small></section><button className="restart" onClick={begin}>重新开始测试</button></main>;
 const career=ranks.career[0], comfort=ranks.comfort[0]; return <main className="report"><button className="plain back" onClick={()=>setStage("result")}>← 返回结果</button><p className="eyebrow">YOUR CITY LIFE / 完整报告</p><h1>你会在<br/><i>{destiny.city.name}</i><br/>活得更像自己。</h1><article><Report title="01 / 你的城市人格" text={`你是偏向「${traits.map(d=>dimensionLabel(d)).join("、")}」的生活方式探索者。你在意的不只是工作好不好，更在意机会、日常和自己能否长期相处。`} /><Report title="02 / 为什么是这座城市" text={`${destiny.city.name} 对你有吸引力，是因为它的${destiny.city.strengths[0]}，恰好与您当前的生活倾向形成了可持续的平衡。这不是命运判断，而是基于本次选择的匹配建议。`} /><Report title="03 / 这座城市可能让你难受的地方" text={`也要诚实地说：${destiny.city.tradeoffs[0]}。真正适合不等于没有摩擦，而是这些摩擦仍值得你用生活里的所得去交换。`} /><Report title="04 / 另外三座关键城市" text={`事业城市是 ${career.city.name}：它更能放大你的职业动能。舒服生活的城市是 ${comfort.city.name}：它更接近日常恢复和空间感。相对最不适配的是 ${ranks.least.city.name}，它与当前偏好的匹配度较低，不代表它不好，只是这一次不够像你。`} /></article><ShareCard city={destiny.city.name} second={ranks.destiny[1].city.name} career={career.city.name} traits={traits.map(d=>dimensionLabel(d))}/></main>;
}
function Report({title,text}:{title:string;text:string}){return <section className="report-section"><h2>{title}</h2><p>{text}</p></section>}
function ShareCard({city,second,career,traits}:{city:string;second:string;career:string;traits:string[]}){return <section className="share"><div className="share-card"><small>MY DESTINY CITY</small><h2>我的命定城市</h2><strong>{city}</strong><p>城市人格：<br/>温和探索型</p><p className="keywords">{traits.join(" · ")}</p><footer>第二命定城市：{second}<br/>事业城市：{career}</footer></div><button onClick={()=>event("share_card_generated")}>生成分享卡 <span>↓</span></button><small>1080 × 1440 分享卡预览</small></section>}
